# Generated by Django 4.1.7 on 2023-03-31 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=250, verbose_name='заголовок')),
                ('body', models.CharField(max_length=250, verbose_name='текст')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='post_pictures/', verbose_name='изображение')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250, verbose_name='текст')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
